#define TEST_SAMPLES_SIZE 106

unsigned char test_samples_text[106][90] = {
	"i want to go marienplatz",
	"when is the next train in muncher freiheit?",
	"when does the next u-bahn leaves from garching forschungszentrum?",
	"from olympia einkaufszentrum to hauptbahnhof",
	"when is the next train from winterstraﬂe 12 to kieferngarten",
	"when is the next rocket from winterstraﬂe 12 to kieferngarte",
	"can you find a connection from garching to hauptbahnhof?",
	"how to get from untere strass‰cker 21 to frˆttmaning",
	"how i can get from marienplatz to garching",
	"connection from boltzmannstraﬂe to kieferngarten",
	"how to get from bonner platz to freimann?",
	"when is the next s-bahn leaving at garching?",
	"how do i get from oez to hbf?",
	"how to get from winterstrasse 12 to frˆttmaning",
	"how do i get from garching forschungszentrum to pasing",
	"theresienstraﬂe to assling",
	"how can i get from theresienstraﬂe to munich east?",
	"when does the next bus starts from garching?",
	"from quiddestraﬂe to garching?",
	"can you find a connection from kurt-eisner-straﬂe to garching forschungszentrum?",
	"can you find a connection from quiddestraﬂe to garching forschungszentrum?",
	"when does the next train leaves at garching?",
	"from hauptbahnhof to garching?",
	"how can i get to glockenbachviertel from garching forschungszentrum?",
	"how i can get from garching to nordfriedhof",
	"how can i get to glockenbachviertel from garching forschungszentrum?",
	"when is the next train leaving in garching forschungszentrum",
	"how can i get from moosach to quiddestraﬂe?",
	"how can i get from moosach to poccistraﬂe?",
	"how can i get from kurt-eisner-straﬂe to garching forschungszentrum?",
	"how can i get from moosach to quiddestraﬂe?",
	"how can i get from moosach to odeonsplatz?",
	"when does the next bus starts at garching?",
	"what's the shortest way from quiddestraﬂe to odeonsplatz?",
	"when is the next bus from ostbahnhof",
	"how i can get from garching to neuperlach sued",
	"when is the next train in munchner freiheit?",
	"how i can get from marienplatz to garching?",
	"how do i get from poccistraﬂe to laim",
	"i want to go garching from marienplatz",
	"how i can get from marienplatz to garching?",
	"how can i get from hauptbahnhof to odeonsplatz",
	"prinzregentenplatz to rotkreuzplatz",
	"i want to go to garching from marienplatz",
	"next train from garching",
	"from prinzregentenplatz to rotkreuzplatz",
	"when is the next subway from garching forschungszentrum",
	"from garching to klinikum",
	"from garching foschungszentrum to odeonsplatz",
	"next bus in garching",
	"when does the train leaving in garching forschungszentrum",
	"next subway from garching forschungszentrum",
	"tell me the next bus from garching",
	"next bus from garching, please.",
	"next bus from garching",
	"next bus from central station",
	"from garching to marienplatz",
	"next bus from garching.",
	"connection from garching to hauptbahnhof?",
	"when does the next bus departs from garching?",
	"find connection from hauptbahnhof to odeonsplatz",
	"when does the next u-bahn departs at garching forschungszentrum?",
	"when does the next u-bahn departs at garching?",
	"when does the next subway departs at garching",
	"when is the next train in garching?",
	"how to get from m¸nchner freiheit to garching ?",
	"implerstraﬂe to ostbahnhof",
	"how can i get from hauptbahnhof to odeonsplatz?",
	"how can i go from garching forschungszentrum to prinzregentenplatz",
	"how can i get from mangfallplatz to garching",
	"how can i get to hohenlindenerstraﬂe",
	"harthaus to hackerbr¸cke",
	"how can i get from feldmoching to garching forschungszentrum?",
	"from marienplatz to petershausen",
	"when is the train from garching to marienplatz",
	"neufahrn to garching",
	"how can i get from mangfallplatz to garching",
	"how can i get to hohenlindenerstr",
	"when is the next bus from garching forschungzentrum",
	"how do i get from spitzingplatz to poccistraﬂe?",
	"how can i get from garching forschungszentrum to marienplatz",
	"how can i get from klinkum to marienplatz?",
	"how to get from alte heide to marienplatz",
	"next train from muenchen freicheit",
	"depart in garching, i assume",
	"when does the next u-bahn depart at garching?",
	"the next bus from garching forschungzentrum",
	"when is the next train in alte heide?",
	"or depart from garching",
	"hello munich city bot! how do i get from m¸nchner freiheit to scheidplatz?",
	"how can i get from garching forschungszentrum to prinzregentenplatz",
	"how can i get from neufahrn to garching",
	"take me to the airport",
	"when does the next u6 leave from garching forschungszentrum",
	"how i can get from munchner freiheit to nordfriedhof?",
	"from harthaus to hackerbr¸cke",
	"when is the train from garching",
	"what is the next train from m¸nchner freiheit",
	"how can i get from theresienstrasse to garching forschungszentrum",
	"how can i get from m¸nchner freiheit to odeonsplatz",
	"from garching to hauptbahnhof",
	"how can i get from garching to odeonsplatz",
	"start: neufahrn end:garching",
	"how can i get from studentenstadt to garching",
	"when is the next bus from garching",
	"take me from hauptbahnhof to odeonsplatz"
};
